import React, { useState } from "react";
import exportTemplateApi from "../../services/exportTemplateApi";

/**
 * @desc WYSIWYG-style editor for creating and customizing Handlebars export templates.
 * Includes a live preview pane and section configuration.
 */
const TemplateEditor = ({ template, onClose, onSave }) => {
  const [formData, setFormData] = useState(
    template || {
      name: "",
      description: "",
      type: "custom",
      templateContent:
        "<h1>{{meeting.title}}</h1>\n<p>{{meeting.summary}}</p>\n<ul>{{#each meeting.attendees}}<li>{{this.name}}</li>{{/each}}</ul>",
      styles:
        "body { font-family: system-ui, sans-serif; padding: 20px; line-height: 1.6; }\nh1 { color: #1e293b; }\np { color: #475569; }",
      branding: {
        primaryColor: "#4f46e5",
        headerText: "Meeting Minutes",
        footerText: "Generated by MeetOnMemory",
      },
      sections: {
        showAttendees: true,
        showActionItems: true,
        showSummary: true,
        showTranscript: false,
        showDecisions: true,
      },
    },
  );

  const [previewHtml, setPreviewHtml] = useState("");
  const [isPreviewing, setIsPreviewing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState(null);

  // Sample data for live preview rendering
  const sampleData = {
    meeting: {
      title: "Q3 Planning Session",
      date: new Date().toISOString(),
      summary:
        "Discussed roadmap priorities, team capacity, and allocated engineering resources for the upcoming quarter.",
      attendees: [{ name: "Alice Smith" }, { name: "Bob Jones" }],
      actionItems: [
        {
          title: "Finalize budget",
          assignee: "Alice",
          deadline: new Date().toISOString(),
          priority: "high",
        },
      ],
    },
  };

  const handlePreview = async () => {
    setIsPreviewing(true);
    setError(null);
    try {
      const res = await exportTemplateApi.previewTemplate({
        templateContent: formData.templateContent,
        meetingData: sampleData,
      });
      setPreviewHtml(res.data?.html || "");
    } catch (err) {
      console.error("Preview failed:", err);
      setError("Failed to render preview. Check your template syntax.");
    } finally {
      setIsPreviewing(false);
    }
  };

  const handleSave = async () => {
    if (!formData.name.trim() || !formData.templateContent.trim()) {
      setError("Template name and content are required.");
      return;
    }

    setIsSaving(true);
    setError(null);
    try {
      if (template?._id) {
        await exportTemplateApi.updateTemplate(template._id, formData);
      } else {
        await exportTemplateApi.createTemplate(formData);
      }
      if (onSave) onSave();
      if (onClose) onClose();
    } catch (err) {
      console.error("Save failed:", err);
      setError("Failed to save template. Please try again.");
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div
      className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[60] p-4"
      data-testid="template-editor-modal"
    >
      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl w-full max-w-6xl h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="p-4 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between bg-gray-50 dark:bg-gray-900/50">
          <div>
            <h2 className="text-xl font-bold text-gray-900 dark:text-white">
              {template ? "Edit Export Template" : "Create New Export Template"}
            </h2>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              Customize Handlebars HTML layout and CSS styles for meeting export
              documents
            </p>
          </div>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={handlePreview}
              disabled={isPreviewing}
              className="px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 text-sm font-medium disabled:opacity-50"
            >
              {isPreviewing ? "Rendering..." : "Preview"}
            </button>
            <button
              type="button"
              onClick={handleSave}
              disabled={isSaving}
              className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 text-sm font-bold shadow"
            >
              {isSaving ? "Saving..." : "Save Template"}
            </button>
            <button
              type="button"
              onClick={onClose}
              aria-label="Close template editor"
              className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 px-2"
            >
              <svg
                className="w-6 h-6"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>
        </div>

        {error && (
          <div className="mx-4 mt-3 p-3 bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 rounded-lg text-xs font-medium">
            {error}
          </div>
        )}

        {/* Editor Body */}
        <div className="flex-1 flex overflow-hidden">
          {/* Left Panel: Code Editor & Fields */}
          <div className="w-1/2 border-r border-gray-200 dark:border-gray-700 flex flex-col overflow-hidden p-4 space-y-3 overflow-y-auto">
            <div>
              <label className="block text-xs font-bold uppercase text-gray-500 dark:text-gray-400 mb-1">
                Template Name
              </label>
              <input
                type="text"
                placeholder="e.g. Executive Board Summary"
                value={formData.name}
                onChange={(e) =>
                  setFormData({ ...formData, name: e.target.value })
                }
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white font-bold text-sm"
              />
            </div>

            <div>
              <label className="block text-xs font-bold uppercase text-gray-500 dark:text-gray-400 mb-1">
                Description
              </label>
              <input
                type="text"
                placeholder="e.g. Formal executive format with action items"
                value={formData.description}
                onChange={(e) =>
                  setFormData({ ...formData, description: e.target.value })
                }
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white text-xs"
              />
            </div>

            <div>
              <label className="block text-xs font-bold uppercase text-gray-500 dark:text-gray-400 mb-1">
                Handlebars HTML Template
              </label>
              <textarea
                placeholder="Handlebars Template (HTML)"
                value={formData.templateContent}
                onChange={(e) =>
                  setFormData({ ...formData, templateContent: e.target.value })
                }
                rows={12}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white font-mono text-xs leading-relaxed resize-none"
              />
            </div>

            <div>
              <label className="block text-xs font-bold uppercase text-gray-500 dark:text-gray-400 mb-1">
                CSS Styles
              </label>
              <textarea
                placeholder="CSS Styles"
                value={formData.styles}
                onChange={(e) =>
                  setFormData({ ...formData, styles: e.target.value })
                }
                rows={6}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white font-mono text-xs leading-relaxed resize-none"
              />
            </div>
          </div>

          {/* Right Panel: Live Preview */}
          <div className="w-1/2 flex flex-col overflow-hidden bg-gray-100 dark:bg-gray-900">
            <div className="p-2.5 bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wider flex items-center justify-between">
              <span>Live Preview</span>
              <span className="text-[10px] text-gray-400">
                Sample Data Rendered
              </span>
            </div>
            <div className="flex-1 overflow-y-auto p-6">
              <div className="bg-white shadow-lg rounded-lg p-6 min-h-full">
                {previewHtml ? (
                  <div dangerouslySetInnerHTML={{ __html: previewHtml }} />
                ) : (
                  <div className="text-center text-gray-400 dark:text-gray-600 py-20 text-sm">
                    Click "Preview" above to render the Handlebars template with
                    sample data.
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TemplateEditor;
